// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined;

export const supabaseConfigError: string | null = (() => {
  if (!SUPABASE_URL?.trim()) {
    return "Не задан VITE_SUPABASE_URL в файле .env";
  }
  if (!SUPABASE_KEY?.trim()) {
    return "Не задан VITE_SUPABASE_PUBLISHABLE_KEY (или VITE_SUPABASE_ANON_KEY) в файле .env";
  }
  if (!SUPABASE_URL.includes("supabase.co")) {
    return "VITE_SUPABASE_URL выглядит некорректно — проверьте адрес проекта Supabase";
  }
  return null;
})();

if (supabaseConfigError && import.meta.env.DEV) {
  console.error("[BuildConnect]", supabaseConfigError);
}

export const supabase = createClient<Database>(
  SUPABASE_URL ?? "",
  SUPABASE_KEY ?? "",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

/** Быстрая проверка доступа к API (для диагностики на старте). */
export async function pingSupabase(): Promise<{ ok: boolean; message?: string }> {
  if (supabaseConfigError) {
    return { ok: false, message: supabaseConfigError };
  }
  const { error } = await supabase.from("companies").select("id").limit(1);
  if (error) {
    return { ok: false, message: error.message };
  }
  return { ok: true };
}
